config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'welcome#home'

  devise_for :users

  resources :shifts

  resources :organisations do
    resources :memberships
  end

end

app/models/organisation.rb
class Organisation < ApplicationRecord
  has_many :memberships, dependent: :destroy
  has_many :users, :through => :memberships

  validates :name, presence: true, uniqueness: true
  validates :hourly_rate, presence: true, format: { with: /\A\d+(?:\.\d{0,2})?\z/ }, numericality: { greater_than: 0, less_than: 1000 }
end

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController
  before_action :set_organisation, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /organisations or /organisations.json
  def index
    @organisations = Organisation.all
  end

  # GET /organisations/1 or /organisations/1.json
  def show
  end

  # GET /organisations/new
  def new
    @organisation = Organisation.new
  end

  # GET /organisations/1/edit
  def edit
  end

  # POST /organisations or /organisations.json
  def create
    @organisation = Organisation.new(organisation_params)

    respond_to do |format|
      if @organisation.save
        @organisation.users << current_user

        format.html { redirect_to root_path, notice: "Organisation was successfully created." }
        format.json { render :show, status: :created, location: @organisation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @organisation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organisations/1 or /organisations/1.json
  def update
    respond_to do |format|
      if @organisation.update(organisation_params)
        format.html { redirect_to root_path, notice: "Organisation was successfully updated." }
        format.json { render :show, status: :ok, location: @organisation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @organisation.errors, status: :unprocessable_entity }
      end
    end

  end

  # DELETE /organisations/1 or /organisations/1.json
  def destroy
    find_memberships_and_shifts_and_delete

    @organisation.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: "Organisation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organisation
      @organisation = Organisation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def organisation_params
      params.require(:organisation).permit(:name, :hourly_rate)
    end

    def find_memberships_and_shifts_and_delete
      Membership.where(organisation_id: @organisation.id).each do |membership| 
        Shift.where(user_id: membership.user_id).delete_all
        membership.destroy
      end
    end
end

app/helpers/organisations_helper.rb
module OrganisationsHelper
end

app/views/organisations/_form.html.erb
<%= form_with(model: organisation) do |form| %>
  <% if organisation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(organisation.errors.count, "error") %> prohibited this organisation from being saved:</h2>

      <ul>
        <% organisation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :hourly_rate %>
    <%= form.text_field :hourly_rate %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/organisations/edit.html.erb
<h2>Edit Organisation</h2>

<%= render 'form', organisation: @organisation %>

<%= link_to 'Delete', @organisation, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/organisations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Organisations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Hourly rate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @organisations.each do |organisation| %>
      <tr>
        <td><%= organisation.name %></td>
        <td><%= organisation.hourly_rate %></td>
        <td><%= link_to 'Show', organisation %></td>
        <td><%= link_to 'Edit', edit_organisation_path(organisation) %></td>
        <td><%= link_to 'Destroy', organisation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Organisation', new_organisation_path %>

app/views/organisations/new.html.erb
<h1>New Organisation</h1>

<%= render 'form', organisation: @organisation %>

<%= link_to 'Back', organisations_path %>

app/views/organisations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @organisation.name %>
</p>

<p>
  <strong>Hourly rate:</strong>
  <%= @organisation.hourly_rate %>
</p>

<%= link_to 'Edit', edit_organisation_path(@organisation) %> |
<%= link_to 'Back', organisations_path %>