config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'welcome#home'

  devise_for :users

  resources :shifts

  resources :organisations do
    resources :memberships
  end

end

app/views/shared/_join_organisation.html.erb
    <p>You aren't a member of any organisations.<br>
    Join an existing one or create a new one.</p>

    <h2>Organisations</h2>

    <% if @organisations.empty? %>
      <p>There aren't any organisations, please create a new one.</p>
    <% end %>

    <ul>
      <% @organisations.each do |organisation| %>
        <li>
        <%= organisation.name %>
        <%= link_to 'Edit', edit_organisation_path(organisation) %>
        <%= link_to 'Join', organisation_memberships_path(organisation.id), method: :post %>
        <%= link_to 'Destroy', organisation, method: :delete, data: { confirm: 'Are you sure?' } %>
        </li>
      <% end %>
    </ul>

app/views/shared/_login.html.erb
<h2>Log in</h2>

<%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password, autocomplete: "current-password" %>
  </div>

  <% if devise_mapping.rememberable? %>
    <div class="field">
      <%= f.check_box :remember_me %>
      <%= f.label :remember_me %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit "Log in" %>
  </div>
<% end %>

<%= link_to 'Sign up', new_user_registration_path %>
<br>
<%= link_to 'Forgot your password?', new_user_password_path %>

app/views/shared/_manage_organisation.html.erb
<h2><%= current_user.membership.organisation.name %></h2>

<%= link_to 'View Shifts', shifts_path %>
<%= link_to 'Edit', edit_organisation_path(current_user.membership.organisation_id) %>
<%= link_to 'Leave', organisation_membership_path(current_user.membership.organisation_id, current_user.membership.id), method: :delete, data: { confirm: 'Are you sure you want to leave?' } %>

app/views/shared/_new_organisation_form.html.erb
<h2>Create organisation</h2>

<%= form_with(model: organisation) do |form| %>
  <% if organisation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(organisation.errors.count, "error") %> prohibited this organisation from being saved:</h2>

      <ul>
        <% organisation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, 'Name:' %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :hourly_rate, 'Hourly rate: $' %>
    <%= form.text_field :hourly_rate %>
  </div>

  <div class="actions">
    <%= form.submit 'Create and Join'%>
  </div>
<% end %>