config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'welcome#home'

  devise_for :users

  resources :shifts

  resources :organisations do
    resources :memberships
  end

end

app/models/shift.rb
class Shift < ApplicationRecord
  belongs_to :user

  validates :start, :finish, presence: true
  validates :break_length, presence: true, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 720 }

  validate :start_finish_check
  validate :break_length_check
  
  def employee_name
    user.name
  end

  def start_date
    start.strftime("%d/%m/%Y")
  end

  def start_time
    start.strftime("%I:%M %p")
  end

  def finish_time
    finish.strftime("%I:%M %p")
  end

  def hours_worked
    # display hrs to 2d.p.
    '%.2f' % hours_worked_unrounded
  end

  def sunday_premium_cost
    if start.sunday? && finish.sunday? 
      hours_worked_unrounded * hourly_rate
    elsif start.sunday?
      # if start on sunday and ends overnight
      calculate_sunday_start_premium
    elsif finish.sunday?
      # if start saturday working overnight into sunday
      calculate_sunday_end_premium
    else
      0
    end
  end

  def cost
    cost = sunday_premium_cost + (hours_worked_unrounded * hourly_rate)
    '%.2f' % cost
  end

  private
    def shift_length_mins
      (finish - start) / 60
    end

    def hours_worked_unrounded
      # break is defined in minutes
      (shift_length_mins - break_length.to_i) / 60
    end

    def hourly_rate
      user.membership.organisation.hourly_rate
    end

    def dates_valid
      begin
        start < finish
      rescue 
        false
      end
    end

    def start_finish_check
      errors.add(:finish, "Please select a time later than the start time") unless dates_valid
    end

    def break_valid
      begin
        break_length <= shift_length_mins
      rescue
        false
      end
    end

    def break_length_check
      errors.add(:finish, "Please check the break length") unless break_valid
    end

    def calculate_sunday_start_premium
      minutes_on_sunday = (start.midnight + 1.day - start) / 60

      if (shift_length_mins - minutes_on_sunday) < break_length
        # reduce minutes on sunday for the break_length
        minutes_on_sunday = shift_length_mins - break_length
      end

      hours_on_sunday = minutes_on_sunday / 60
      hours_on_sunday * hourly_rate
    end

    def calculate_sunday_end_premium
      minutes_on_sunday = (finish - finish.beginning_of_day) / 60

      if minutes_on_sunday > break_length
        hours_on_sunday = (minutes_on_sunday - break_length) / 60
        hours_on_sunday * hourly_rate
      else
        # if the break_length exceeds their mins worked on sunday then they get nothing
        0
      end
    end

end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  before_action :set_shift, only: %i[show edit update destroy]
  # user must be logged in to do anything with shifts
  before_action :authenticate_user!
  before_action :redirect_if_no_org

  # GET /shifts or /shifts.json
  def index
    @shifts = Shift.order('start desc')
    @shift = Shift.new
  end

  # GET /shifts/1 or /shifts/1.json
  def show
  end

  # GET /shifts/new
  def new
    @shift = Shift.new
  end

  # GET /shifts/1/edit
  def edit
  end

  # POST /shifts or /shifts.json
  def create
    @shift = Shift.new
    ShiftCreator.call(shift_params, @shift, user: current_user)

    respond_to do |format|
      if @shift.save
        format.html { redirect_to shifts_path, notice: "Shift was successfully created." }
        format.json { render :show, status: :created, location: @shift }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @shift.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shifts/1 or /shifts/1.json
  def update
    ShiftCreator.call(shift_params, @shift)

    respond_to do |format|
      if @shift.save
        format.html { redirect_to @shift, notice: "Shift was successfully updated." }
        format.json { render :show, status: :ok, location: @shift }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @shift.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shifts/1 or /shifts/1.json
  def destroy
    @shift.destroy
    respond_to do |format|
      format.html { redirect_to shifts_url, notice: "Shift was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shift
      @shift = Shift.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shift_params
      params.require(:shift).permit(:date, :start, :finish, :break_length)
    end

    def redirect_if_no_org
      redirect_to root_path unless current_user.membership
    end
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/views/shifts/_form.html.erb
<%= form_with(model: shift) do |form| %>
  <% if shift.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shift.errors.count, "error") %> prohibited this shift from being saved:</h2>

      <ul>
        <% shift.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date, use_two_digit_numbers: true, order: [:day, :month, :year] %>
  </div>

  <div class="field">
    <%= form.label :start %>
    <%= form.time_select :start, :ignore_date => true, minute_step: 15 %>
  </div>

  <div class="field">
    <%= form.label :finish %>
    <%= form.time_select :finish, :ignore_date => true, minute_step: 15 %>
  </div>

  <div class="field">
    <%= form.label :break_length %>
    <%= form.number_field :break_length, :value => 0 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shifts/edit.html.erb
<h1>Editing Shift</h1>

<%= render 'form', shift: @shift %>

<%= link_to 'Show', @shift %> |
<%= link_to 'Back', shifts_path %>

app/views/shifts/index.html.erb
<h2><%= current_user.membership.organisation.name %></h2>
<h3>Shifts</h3>

<%= form_with(model: @shift) do |form| %>
  <% if @shift.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shift.errors.count, "error") %> prohibited this shift from being saved:</h2>

      <ul>
        <% @shift.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <table>
    <thead>
      <tr>
        <th>Employee name</th>
        <th>Shift date</th>
        <th>Start time</th>
        <th>Finish time</th>
        <th>Break length (minutes)</th>
        <th>Hours worked</th>
        <th>Shift cost</th>
        <th>Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @shifts.each do |shift| %>
        <% if shift.user.membership.organisation_id == current_user.membership.organisation_id %>
        <tr>
          <td><%= shift.employee_name %></td>
          <td><%= shift.start_date %></td>
          <td><%= shift.start_time %></td>
          <td><%= shift.finish_time %></td>
          <td><%= shift.break_length %></td>
          <td><%= shift.hours_worked %></td>
          <td>$<%= shift.cost %></td>
          <td><% if shift.user == current_user %>
            <%= link_to 'Edit', edit_shift_path(shift) %>
            <%= link_to 'Delete', shift, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %></td>
        </tr>
        <% end %>
      <% end %>
    </tbody>

    <tfoot>
        <td><%= current_user.name %></td>

        <td><div class="field">
          <%= form.date_select :date, use_two_digit_numbers: true, order: [:day, :month, :year] %>
        </div></td>

        <td><div class="field">
          <%= form.time_select :start, ignore_date: true, minute_step: 15 %>
        </div></td>

        <td><div class="field">
          <%= form.time_select :finish, ignore_date: true, minute_step: 15 %>
        </div></td>

        <td><div class="field">
          <%= form.number_field :break_length, value: 0 %>
        </div></td>

        <td colspan="3"><div class="actions">
          <%= form.submit %>
        </div></td>
    </tfoot>
  </table>
<% end %>

<br>

app/views/shifts/new.html.erb
<h1>New Shift</h1>

<%= render 'form', shift: @shift %>

<%= link_to 'Back', shifts_path %>

app/views/shifts/show.html.erb
<p>
  <strong>Start:</strong>
  <%= @shift.start %>
</p>

<p>
  <strong>Finish:</strong>
  <%= @shift.finish %>
</p>

<p>
  <strong>Break length:</strong>
  <%= @shift.break_length %>
</p>

<p>
  <strong>User:</strong>
  <%= @shift.user_id %>
</p>

<%= link_to 'Edit', edit_shift_path(@shift) %> |
<%= link_to 'Back', shifts_path %>